### ISSUE TITLE
`LruTimestamp::get_timestamp()` can't compute result

### ISSUE THREAD

**Issue by ahrens** [fitzgen/associative-cache#16]
context:
```rust
pub trait LruTimestamp {
    type Timestamp: PartialOrd;
    fn get_timestamp(&self) -> &Self::Timestamp;
}
```
I think this means `LruTimestamp::get_timestamp()` has to return a reference to something inside `self`, so it can't compute the timestamp.  For example, if I want the timestamp to be `self.member1 + self.member2`.  Or in my case, `self` is `#[repr(packed)]`, so I can't[*] return a reference to a member; I want to do the unaligned dereference and return the value.

[*] or at least, rustc says it will be disallowed in a future release

I think that the interface could be changed to:
```rust
pub trait LruTimestamp {
    type Timestamp: PartialOrd;
    fn get_timestamp(&self) -> Self::Timestamp; // removed &
}
```
And then you can still return a reference to something inside `self` when desired, by defining the `Timestamp` type to be a reference, e.g.:

```rust
impl<T> LruTimestamp for WithLruTimestamp<T> {
    type Timestamp = &Cell<Instant>; // added &
    fn get_timestamp(&self) -> Self::Timestamp { // removed &
        &self.timestamp
    }
}
```

I'm not sure exactly how to do this as a non-breaking change, maybe add a new trait, `LruTimestampByValue`?

**Comment by ahrens** [comment]
I realized that I can `impl Replacement` directly, rather than using LruTimestamp.  So I can define my own trait similar to LruTimestamp that does what I want.  I'd be happy to open a PR to add this to the associative-cache crate, if the maintainers would like.

```rust
pub trait LruTimestampOwned {
    type Timestamp: PartialOrd;
    fn get_timestamp(&self) -> Self::Timestamp;
    fn update_timestamp(&self);
}

#[derive(Default)]
struct LruReplacementOwned;

impl<V, C> Replacement<V, C> for LruReplacementOwned
where
    C: Capacity,
    V: LruTimestampOwned,
{
    #[inline]
    fn choose_for_replacement<'a>(
        &mut self,
        candidates: impl ExactSizeIterator<Item = (usize, &'a V)>,
    ) -> usize
    where
        V: 'a,
    {
        candidates
            .fold(None, |lru, (index, value)| {
                let timestamp = value.get_timestamp();
                match lru {
                    Some((t, i)) if t < timestamp => Some((t, i)),
                    _ => Some((timestamp, index)),
                }
            })
            .expect("candidates should not be empty")
            .1
    }

    #[inline]
    fn on_hit(&self, value: &V) {
        value.update_timestamp();
    }

    #[inline]
    fn on_insert(&self, value: &V) {
        value.update_timestamp();
    }
}
```

**Comment by fitzgen** [comment]
Note that the original suggestion won't work unless you use generic associated types because the reference in the associated type needs a lifetime but the lifetime needs to match the `&self`'s lifetime from the method which isn't available in the associated type.

Luckily generic associated types became stable relatively recently.

I'd accept a PR that made this change and added a `rust-version` metadata to `Cargo.toml` to require a new enough Rust version that has GAT support.

```rust
pub trait LruTimestampOwned {
    type Timestamp<'a>: PartialOrd;
    fn get_timestamp(&self) -> Self::Timestamp;
}
```

**Comment by fitzgen** [comment]
> we can make a trait that handles both owned and referenced `Timestamp` types, taking advantage of GAT.

Correct.

> To handle backwards compatibility, we would give the trait a new name, e.g. `LruTimestampOwned` (although it can be owned or referenced).

We don't need to worry about backwards compat, it can be a breaking change.

**Comment by ahrens** [comment]
FYI, looks like the compiler+clippy wants it to be:
```rust
pub trait LruTimestamp2 {
    type Timestamp<'a>: PartialOrd where Self: 'a;
    fn get_timestamp(&self) -> Self::Timestamp<'_>;
    fn update_timestamp(&self);
}
```
